### ISSUE TITLE
Quality of signal is low, no RDS

### ISSUE THREAD

**Issue by JakVorobey** [RTVDXRO/NXP-TEF6686-Arduino-Radio#2]
Hello !
I just received module with TEF6686 from aliexpress and created test board using schematic and scripts from this project.
What i got: soft works ! But quality of signal is low (~30 dBf), all options are default. 
I use simple wire as antenna - just as on the drawing. Maybe wire is not enough ?
here are pictures of the test board : 
![IMG_0923](https://user-images.githubusercontent.com/86143585/122634042-92444280-d0e4-11eb-8a6b-b2a853997317.jpg)
![board](https://user-images.githubusercontent.com/86143585/122634045-97a18d00-d0e4-11eb-8cb9-f663a69c6c1c.jpg)
 
Here is program screenshot :
![screen](https://user-images.githubusercontent.com/86143585/122634083-e18a7300-d0e4-11eb-9242-7a09880148d6.jpg)

Thanks for help !

**Comment by JakVorobey** [comment]
There is a capacitor near antenna 10nF
Added coil 0.22µH between ANT and GND - didn't help :-(

**Comment by JakVorobey** [comment]
Tried this antenna with USB-powered (5v) amplifier : 
![IMG_0924](https://user-images.githubusercontent.com/86143585/122636185-82caf680-d0f0-11eb-840d-326cf62c41cf.jpg)
![IMG_0928](https://user-images.githubusercontent.com/86143585/122636191-88284100-d0f0-11eb-9a8d-581506f9ce35.jpg)
Made SMA connector to this antenna and connected to my board : 
![IMG_0926](https://user-images.githubusercontent.com/86143585/122636209-9f672e80-d0f0-11eb-9607-347eaefa0d8c.jpg)

Result is worse : 
![screen2](https://user-images.githubusercontent.com/86143585/122636543-7e9fd880-d0f2-11eb-85f3-b6ff2add7dcd.jpg)

**Comment by JakVorobey** [comment]
Then i decided to cut SMA ground 
![scheme1](https://user-images.githubusercontent.com/86143585/122636927-7d6fab00-d0f4-11eb-8c51-f60968cc04a0.jpg)
and got this result : 
![screen3](https://user-images.githubusercontent.com/86143585/122636947-98421f80-d0f4-11eb-9192-86095ad8b07e.jpg)

**Comment by RTVDXRO** [comment]
I personally use an F plug glued to the ground as close as possible to the antenna input of the module with the central pin connected directly to the input and it works perfectly. Inside the mode there are FM / AM filters on the input, no capacitor is needed in series. Make tests first with a 72 cm long wire as an antenna. The one with power supply in your pictures, by size, seems inappropriate for me. FM. Then try a serious antenna! See here: http://ham-radio.com/k6sti/

**Comment by RTVDXRO** [comment]
I personally use an F plug with respect to the ground as close as possible to the antenna input of the module with the central pin connected directly to the input and it works perfectly. Shorter conection is better. Inside the module there are FM / AM filters on the input, so no capacitor is needed in series. As advice, make tests first with a 72 cm long wire as an antenna. The one with power supply in your pictures, by size, seems inappropriate for FM band. Then try a serious antenna! See here: http://ham-radio.com/k6sti/   .  About RDS, I checked the sketches I uploaded just before I answered and it works OK. But if the input signal is bad, it is very possible that the RDS will not enter. But if you have a good signal and it does not enter, you may have a module that is not with TEF6686 but with TEA6851. This is what the one with TEF6686 marked F8602 looks like inside: https://i.imgur.com/KZ22ei6.jpg

**Comment by JakVorobey** [comment]
I opened midule and found F8602 chip inside ! This is not TEF6686, right ?

![IMG_0938](https://user-images.githubusercontent.com/86143585/122680202-cc056e00-d1f6-11eb-8ad0-d267b7f590db.jpg)

Maybe this is a reason of bad quality ?

**Comment by RTVDXRO** [comment]
Nope ... It is TEF6686! F8602 is the marking for TEF6686 but from the picture I see that you hit a 4 MHz Quartz module. So, you have to edit the sketch and choose the 4 Mhz quartz line instead of the 9.12 Mhz: line.  This way ...
// 0x09, 0x40, 0x04, 0x01, 0x00, 0x8C, 0xA0, 0x00, 0x00, 0x00, // 9216 MHz crystal reference
   0x09, 0x40, 0x04, 0x01, 0x00, 0x3D, 0x09, 0x00, 0x00, 0x00, // 4000 MHz crystal reference 
Happy DXing now !
:)

**Comment by JakVorobey** [comment]
With removed metal case and no capacitor in series this works :-) I also cut wire to 72 cm.
By the way, no difference what setting for crystal I use - 9216 or 4000 - I tried both - result is the same : 
![screen4](https://user-images.githubusercontent.com/86143585/122778225-75129e00-d2b5-11eb-9cdf-b0ff8345541e.jpg)

Thank you for the advise !

**Comment by JakVorobey** [comment]
Can you recommend settings for the place with bad receiving conditions ? I'm going to test this in about 80 km from city ...

**Comment by RTVDXRO** [comment]
If you do not have strong stations in the area that can cause intermodulations (overload) you can try to check/togle RF + and/or IF + to get maximum RF gain (15dB) from internal input LNA stage in TEF6686. Also you can togle the AGC threshold to "high" or "highest". If you select "Ant3" as written in the readme and also in sketch, you will activate "Channel EQ" advised for improved field performance. Play with these settings on weak, critical fringe signals, until you get maximum performance in your local conditions. As for the fact that it doesn't matter the setting of the frequency in the sketch according to the quartz on the module is a nonsense. Comment  ( put //  before the line ) or completely delete the line for 9.12 Mhz..  And don't forget to reset the Arduino board after each write.  You got a nice toy. Play with it!  That's all. :)

**Comment by JakVorobey** [comment]
Thank you so much ! 
Will try ;-)

**Comment by BrunoAllison974** [comment]
Onde eu consigo um telf6686 original ou de ótima qualidade

**Comment by kilber22** [comment]
comecei a 2 meses so o q nao consegui  foi o visor ic funcionar

**Comment by kilber22** [comment]
quanto a qualidade de recepçao se o notbook estiver ligado na energia nao vai funcionar , a fonte aqui no meu not faz com q estacoes distantes pare de pegar.
