### ISSUE TITLE
Volume control is not working

### ISSUE THREAD

**Issue by Mek7** [RTVDXRO/NXP-TEF6686-Arduino-Radio#3]
Hi,
I got a TEF6686 module from aliexpress, hooked it up and it is working.
The module is with TEF6686 v102 (F8602) and looks exactly the same as the photo in this github repository.
There are three versions of NXP-GTK here and I am not sure why and what's the difference between them. However, when I used TEF6686GTK102mp.ino with any version of NXP-GTK, volume slider did nothing (at least nothing audible).
When I used the .ino file from marsel90's repository, volume slider worked OK.
Another question - squelch does not work with either .ino file, is this supported at all by the TEF chip?

**Comment by RTVDXRO** [comment]
Look in the readme first! I wrote: "Audio output level is fixed -> 0dB or +3dB". :) And it's not "an issue " at all. That's what I decided based on my needs, my experience as a RadioTV engineer ... and my taste. :) And there is a reason. Most professional and/or Hi-End tuners do not have volume and/or tone adjustment, or if they do, they have a bypass option, usually having a fixed, neutral, calibrated line output, volume adjustment and tone corrections being made in the following devices/stages of the audio chain. But the sketch can be easily modified so that the volume slider makes the output variable and not fixed. Likewise for squelch. In a professional audio chain, the sound is kept as unaltered, flat, as "identical" as possible in relation to the source, with minimal possible distortions, not according to everyone's subjective ear! :)  Thank you testing my sketch !

**Comment by Mek7** [comment]
I understand, thanks for your explanation. But I still think it kind of defeats the purpose of volume slidet in the NXP-GTK software. Still, who uses other stuff in the audio chain, will just keep volume at 100% and not touch it in the NXP-GTK software.
Squelch didn't work in other sketches I tried either (like the marsel90's) and I didn't see it mentioned in the TEF datasheet so I thought that's not supported at all.

**Comment by RTVDXRO** [comment]
Replace case "V" in the sketch with this: 
```
case 'Y':  // Audio volume scaler
          volume = atoi(buff + 1);
          if (volume == 0) {
            // Set_Cmd(48, 10, 1, 0);  // 0 dB
            Set_Cmd(48, 11, 1, 1);  // nmute
            Set_Cmd(48, 12, 1, 0);
            Set_Cmd(48, 13, 1, 128, 04);
            Set_Cmd(32, 32, 1, 0);
          } else {
            int Setvolume = map(volume, 0, 100, -599, 50);
            Set_Cmd(48, 10, 1, Setvolume);
            // Set_Cmd(48, 10, 1, 20);  // +2 dB
            Set_Cmd(48, 11, 1, 0);  // unmute
            Set_Cmd(48, 12, 1, 0);
            Set_Cmd(48, 13, 1, 128, 04);
            Set_Cmd(32, 32, 1, 0);
          }
          Serial.print("Y");
          Serial.println(volume);
          break;
```

**Comment by RTVDXRO** [comment]
Replace case "Y" in the sketch with this: 
```
case 'Y':  // Audio volume scaler
          volume = atoi(buff + 1);
          if (volume == 0) {
            // Set_Cmd(48, 10, 1, 0);  // 0 dB
            Set_Cmd(48, 11, 1, 1);  // mute
            Set_Cmd(48, 12, 1, 0);
            Set_Cmd(48, 13, 1, 128, 04);
            Set_Cmd(32, 32, 1, 0);
          } else {
            int Setvolume = map(volume, 0, 100, -599, 50);
            Set_Cmd(48, 10, 1, Setvolume);
            // Set_Cmd(48, 10, 1, 20);  // +2 dB
            Set_Cmd(48, 11, 1, 0);  // unmute
            Set_Cmd(48, 12, 1, 0);
            Set_Cmd(48, 13, 1, 128, 04);
            Set_Cmd(32, 32, 1, 0);
          }
          Serial.print("Y");
          Serial.println(volume);
          break;
```

**Comment by RTVDXRO** [comment]
Don't forget that the GTK graphic interface was thought by its author Konrad Kosmatka for SONY XDR-F1HD !  I just adapted his excellent work to be compatible with my sketches for TEF668X. If you want to have the volume slider working just replace case "Y" in the sketch with this: ... 
```
case 'Y':  // Audio volume scaler
          volume = atoi(buff + 1);
          if (volume == 0) {
            // Set_Cmd(48, 10, 1, 0);  // 0 dB
            Set_Cmd(48, 11, 1, 1);  // mute
            Set_Cmd(48, 12, 1, 0);
            Set_Cmd(48, 13, 1, 128, 04);
            Set_Cmd(32, 32, 1, 0);
          } else {
            int Setvolume = map(volume, 0, 100, -599, 50);
            Set_Cmd(48, 10, 1, Setvolume);
            // Set_Cmd(48, 10, 1, 20);  // +2 dB
            Set_Cmd(48, 11, 1, 0);  // unmute
            Set_Cmd(48, 12, 1, 0);
            Set_Cmd(48, 13, 1, 128, 04);
            Set_Cmd(32, 32, 1, 0);
          }
          Serial.print("Y");
          Serial.println(volume);
          break;
```

**Comment by Mek7** [comment]
Will try, thank you.

**Comment by RTVDXRO** [comment]
Anytime!

**Comment by Mek7** [comment]
Yes, it's working. I'm closing this "issue".
